### ISSUE TITLE
Experience with Java language server?

### ISSUE THREAD

**Issue by weilbith** [lvimuser/lsp-inlayhints.nvim#10]
Hey 👋🏾 
Thanks for this nice standalone plugin. 🙏🏾 

I'm wondering why this doesn't work for Java with the Eclipse JDTLS server. According to their code and CHANGELOG they have support for parameter inlay hints. But they don't show up. I'm very certain that my server version is recent enough (`--version` output it weird). But I'm wondering if I need to enable a setting or so.

Unfortunately I'm a bit clueless. Any experience or hints?

**Comment by lvimuser** [comment]
Let me know how it goes

**Comment by weilbith** [comment]
Wow. That was incredibly fast including all the research. Thank you very much!

So, yes it works. Somehow. I can see hints now which definitely haven't existed before. But vary sparely and inconsistent. Example: there is a code section with a singular builder function call sequence. For some I can see the parameter hint, for others not. Very confusing...
But I'm sure this is a server problem. This server does many awkward things. 😑 
I'll try to play around with the configuration you linked. Maybe this improves it.
