### ISSUE TITLE
Extra whitespace on rust-analyzer (anticonceal)

### ISSUE THREAD

**Issue by etrnal70** [lvimuser/lsp-inlayhints.nvim#21]
I don't know whether this bug is from the neovim PR or the plugin, but i just report it anyway. Feel free to close this if i'm wrong.

Looks like it only happens on newly defined variable type hint

![image](https://user-images.githubusercontent.com/5826834/190933510-6b4fe27c-dde7-4aa2-8f69-173edc0235c5.png)

**Comment by etrnal70** [comment]
Since inline virtual text got some movement in core, i believe it's time to try this out again lol. On current RA version (`rust-analyzer 1 (3a27518fe 2023-04-30)`) there are multiple commas on certain type

![image](https://user-images.githubusercontent.com/5826834/236675130-6bb1315e-5ea6-4e2a-8502-8c3531d42e83.png)

For example, this is on vscode

![image](https://user-images.githubusercontent.com/5826834/236675227-fddc5304-977e-4202-a017-57a1dd2b8a5b.png)

**Comment by lvimuser** [comment]
Thanks for the report, I believe it's fixed on commit 84ca3abe8aaecbb5b30ad89e4701d4a9c821b72c 

I'll be closing this in favor of #46.
