### ISSUE TITLE
Hints show at the end of the line

### ISSUE THREAD

**Issue by WhyNotHugo** [lvimuser/lsp-inlayhints.nvim#23]
Hints render at the end of the line, instead of inline. I'm using neovim 0.8.0 (stable release).

My config:

```lua
require("lsp-inlayhints").setup()

vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(args)
    if not (args.data and args.data.client_id) then
      return
    end

    local bufnr = args.buf
    local client = vim.lsp.get_client_by_id(args.data.client_id)
    require("lsp-inlayhints").on_attach(client, bufnr)
  end,
  desc = "lsp-inlayhints",
})
```

Screenshot:

![image](https://user-images.githubusercontent.com/730811/195379834-0e5af233-b2ec-4bdd-9ed1-e613a2311a0b.png)

Any ideas what could be wrong?

**Comment by polyzen** [comment]
https://github.com/lvimuser/lsp-inlayhints.nvim/issues/17#issuecomment-1242142570
