### ISSUE TITLE
Can't seem to get inlay hints to show up

### ISSUE THREAD

**Issue by nerdo** [lvimuser/lsp-inlayhints.nvim#24]
I've tried to google and search and figure this out but I can't seem to figure out what I'm doing wrong.

I have installed and configured this but don't seem to be getting any inlay hints. I've tried a few different languages (php, typescript, lua, go) and I'm not getting anything for any of them.

I have an nvchad-based neovim setup (https://nvchad.com/).

My full, custom config is here (https://github.com/nerdo/nvchad-customizations)

The setup code I have for inlayhints is this:

```lua
require('lsp-inlayhints').setup()

vim.api.nvim_create_augroup("LspAttach_inlayhints", {})
vim.api.nvim_create_autocmd("LspAttach", {
	group = "LspAttach_inlayhints",
	callback = function(args)
		if not (args.data and args.data.client_id) then
			return
		end

		local bufnr = args.buf
		local client = vim.lsp.get_client_by_id(args.data.client_id)
		require("lsp-inlayhints").on_attach(client, bufnr)
	end,
})
```

I pretty much copied and pasted from the lsp inlayhints page as far as a config for neovim 0.8+.

I've put in a debug print right before the `on_attach` call to ensure it's getting to that point, and it is.

But I don't seem to see any difference when this plugin is installed and running, even after toggling it with `lua require('lsp-inlayhints').toggle()`.

Can someone point me in the right direction? What am I doing wrong?

**Comment by lvimuser** [comment]
Probably missing configuration for the server.

For lua, you need to set `hint.enable` to `true`: https://github.com/sumneko/lua-language-server/wiki/Settings#hintenable

**Comment by nerdo** [comment]
Thanks! I don't know how I missed that in the docs 😬
