### ISSUE TITLE
How to change formatting style to be like rust-tools?

### ISSUE THREAD

**Issue by amaanq** [lvimuser/lsp-inlayhints.nvim#25]
I am on the anticonceal branch, and the current default style is like the following: ` : ReturnType <- (args...)`

I would like it to be the style of rust-tools, where it depends if there's arguments or not (and I'd like to remove the first colon)
with args: ` <- (args...) => ReturnType`
without args: ` => ReturnType`

let me know if this is possible, and if so, how, thanks!

**Comment by lvimuser** [comment]
Have you tried the following options?

```
prefix = "<- ",
separator = ", ",
remove_colon_start = false,
remove_colon_end = true,
labels_separator = "  ",
```
