### ISSUE TITLE
When i changed to the anticonceal branch inlay hints were disappeared 

### ISSUE THREAD

**Issue by amm834** [lvimuser/lsp-inlayhints.nvim#27]
`main` is working well but ``anitconceal` didn't.
What I wanna see is that something like Jetbrain's inlay hint style but they shown at the end of line

**Comment by sinetodev** [comment]
Probably it's because we need to build Neovim from source and apply a patch. See https://github.com/lvimuser/lsp-inlayhints.nvim/issues/17#issuecomment-1242935584

**Comment by amm834** [comment]
Thank you, my life is suffering with that lmao 🤣

**Comment by amm834** [comment]
Ok thanks
