### ISSUE TITLE
`rust-analyzer`: type hints joined with `, `

### ISSUE THREAD

**Issue by Defmc** [lvimuser/lsp-inlayhints.nvim#31]
`rust-tools.nvim`'s returning an error for type hints to me, so I've tried to setup this plugin. Here is my config:
```lua
local server_configs = {
    ["clangd"] = {
        --- ....
    },
    ["rust-analyzer"] = {
        imports = {
            granularity = {
                group = "module",
            },
            prefix = "self",
        },
        cargo = {
            buildScripts = {
                enable = true,
            },
        },
        procMacro = {
            enable = true,
        },
        inlayHints = {
            enabled = true,
            typeHints = {
                enable = true,
            },
        },
    },
}
```
Here is my lsp setup & attach event:
```lua
mason_lsp.setup_handlers({
    function(svr)
        lsp_cfg[svr].setup({
            on_attach = function(_, _) end,
            capabilities = capabilities, -- global to `lspserver.protocol.make_client_capabilities()`
            settings = server_configs[svr],
        })
    end,
})

require("lsp-inlayhints").setup()
require("vim").api.nvim_create_augroup("LspAttach_inlayhints", {})
require("vim").api.nvim_create_autocmd("LspAttach", {
    group = "LspAttach_inlayhints",
    callback = function(args)
        if not (args.data and args.data.client_id) then
            return
        end

        local bufnr = args.buf
        local client = require("vim").lsp.get_client_by_id(args.data.client_id)
        require("lsp-inlayhints").on_attach(client, bufnr)
        require("nvim-navic").attach(client, bufnr)
    end,
})
```
The parameter name hints is working, but the type hints seem to handle each token as a different type:

![issue](https://user-images.githubusercontent.com/76194400/209567392-8dadcbab-67f2-4492-aacd-1ac11f824963.png)

**Comment by lvimuser** [comment]
Did you check the configuration section?
https://github.com/lvimuser/lsp-inlayhints.nvim#default-configuration

In particular, 
```
separator = ", ",
remove_colon_start = false,
remove_colon_end = false,
```

**Comment by Defmc** [comment]
Yes. With `remove_color_{start/end}` set to true, nothing has changed. When I set `separator` to `""` the type hints looks better only for lines that need a hint.
![issue](https://user-images.githubusercontent.com/76194400/209850300-556c1a45-aa97-4f8d-99bd-0d2fefdae217.png)

**Comment by trueegorletov** [comment]
I should upvote this issue. Have the same behavior with `rust-analyzer`, and it does look like `remove_colon_start` and `remove_colon_end` give no sense being set neither `true` or `false`.
Installing or uninstalling `rust-tools.nvim` also doesn't fix this problem. Didn't test any other language servers, but maybe,there is a difference between formats which are used to present type hinting information by `rust-analyzer` and rest LSP servers?

**Comment by emilnuutinen** [comment]
I believe this is related to a recent rust-analyzer update, because rust-tools plugin is broken too [simrat39/rust-tools.nvim/issues/300](https://github.com/simrat39/rust-tools.nvim/issues/300).

Setting locationLinks to false seems to fix the rendering of inlay hints:

```lua
["rust-analyzer"] = {
      inlayHints = { locationLinks = false },
}
```

**Comment by lvimuser** [comment]
Can someone confirm #34 works?

**Comment by emilnuutinen** [comment]
> Can someone confirm #34 works?

Yes, this fixed the problem.
