### ISSUE TITLE
Help for Python

### ISSUE THREAD

**Issue by kiyoon** [lvimuser/lsp-inlayhints.nvim#33]
Hi,

Does this support Python type hints with pyright? I don't know how to enable this..

This is the only reason I still couldn't remove CoC so any help will be very appreciated!!

**Comment by lvimuser** [comment]
Out of scope for this plugin. Thing is, `pyright` doesn't implement inlayHints.
The `coc-pyright` plugin implements additional features (check its readme).

See also:
https://github.com/fannheyward/coc-pyright/commit/1f36838eaacc0d564946733e847a785709550966
https://www.npmjs.com/package/@zzzen/pyright-internal

**Comment by kiyoon** [comment]
@lvimuser Thanks a lot for the pointer. I didn't know this and it's very interesting..

At the moment I don't want to hack it to make it work with native LSP so what I did was just installing `coc.nvim`, `coc-pyright` and disable everything else than inlay hints on the CoC side. It's not efficient but it works..
