### ISSUE TITLE
Files attached to null-ls instead of the LSP providing inlay hints

### ISSUE THREAD

**Issue by kingavatar** [lvimuser/lsp-inlayhints.nvim#41]
Hi @lvimuser, thank you for creating such a useful plugin. I have been enjoying using it with LazyVim. However, I have encountered an issue where sometimes files get attached to null-ls instead of the LSP that provides inlay hints. Currently, I am resolving this issue by modifying the code to check for null-ls clients and assign the first non-null-ls client found. While this solution works for me, I am unsure if there is a better way to handle multiple LSP clients.

Here is the code I added to the plugin:

```lua
if store.b[bufnr].client.name == "null-ls" then
    for _, client in pairs(vim.lsp.get_active_clients { bufnr = bufnr }) do
      if client.name ~= "null-ls" then
        store.b[bufnr].client = { name = client.name, id = client.id }
      end
    end
  end
```
If you think this solution is appropriate, I can create a pull request to implement it and resolve this issue. Thank you for your consideration.

**Comment by lvimuser** [comment]
I don't think that's a good idea. Use the `LspAttach` event (see readme):

```lua
if not (args.data and args.data.client_id) then
  return
end

local bufnr = args.buf
local client = vim.lsp.get_client_by_id(args.data.client_id)
if client.name == "null-ls" then
  return
end
require("lsp-inlayhints").on_attach(client, bufnr)
```
