### ISSUE TITLE
Latest update breaks plugin

### ISSUE THREAD

**Issue by chrisgrieser** [lvimuser/lsp-inlayhints.nvim#42]
one of the latest updates seems to break the plugin. I get the following error, and no more inlay hints
![CleanShot 2023-04-22 at 16 31 33@2x](https://user-images.githubusercontent.com/73286100/233790843-9a890ce0-a345-415b-874d-09af391f0984.png)

**Comment by emilnuutinen** [comment]
Same here. The [latest commit](https://github.com/lvimuser/lsp-inlayhints.nvim/commit/66f234be14b340cc87205c7ba5c5489f86c65e9d) seems to be the issue. Reverting that change fixed the plugin for me.

**Comment by lvimuser** [comment]
fixed on #44
