### ISSUE TITLE
enabled_at_startup doesn't seem to work correctly

### ISSUE THREAD

**Issue by tsakirist** [lvimuser/lsp-inlayhints.nvim#50]
When `enabled_at_startup` is **false** in setup, calling `require"lsp-inlayhints".toggle()` doesn't seem to do anything. Which means I cannot on-demand load the inlay hints.

 As a work-around I've set `enabled_at_startup` to **true** and manually calling `toggle()` once to hide them. The attach on the LSP happens on a different file not depicted in this config.

```lua
local M = {}

function M.setup()
    require("lsp-inlayhints").setup {
        enabled_at_startup = true,
        debug_mode = true,
    }

    -- Disable inlay-hints at startup since the config option doesnt seem to work
    require("lsp-inlayhints").toggle()

    local utils = require "tt.utils"
    utils.map("n", "<leader>it", require("lsp-inlayhints").toggle, { desc = "Toggle LSP inlay hints" })
end

return M
```

Am I missing something or this setting just doesn't work?

**Comment by hffmnn** [comment]
Hi @tsakirist,

I have the same problem. Your workaround doesn't work for me. Because you closed the issue: Did you make it work without the workaround?

**Comment by tsakirist** [comment]
Hi @hffmnn, I didn't bother fixing it but instead I replaced this plugin with neovim's upstream lsp inlay hints implementation.

**Comment by hffmnn** [comment]
Hi @tsakirist. Thanks a lot for the info.
