### ISSUE TITLE
Error after switching to main branch

### ISSUE THREAD

**Issue by ChristianChiarulli** [lvimuser/lsp-inlayhints.nvim#6]
![image](https://user-images.githubusercontent.com/29136904/182038289-dc3bca3f-7d3e-4f38-819c-56a642f0b268.png)

**Comment by lvimuser** [comment]
There was a typo in the last commit, so I force pushed. Doesn't seem related though.

Did it happen just after attaching?

**Comment by ChristianChiarulli** [comment]
Yup that fixed it
